### ISSUE TITLE
NSFW media require authentication to access

### ISSUE THREAD

**Issue by wopian** [manami-project/modb-kitsu#3]
Kitsu excludes NSFW entries from the API unless an account has NSFW content enabled in their settings.

This leaves 1,322 media untracked from Kitsu (16802 total)

https://kitsu.docs.apiary.io/#introduction/authentication

**Comment by manami-project** [comment]
Hello @wopian,

thank you for you interest in this project. That is true. As far as I know MAL is the only meta data provider showing NSFW content withouta a login necessary. I never wanted to create an account on one of the sites and add authentication to the downloaders.
It was always okay for me to not list NSFW content.
